""" Test the Gibbs sampler on real data. """

__author__ = "arnaud.rachez@gmail.com"

import os
import logging
logging.basicConfig(filename='res.out', level=logging.INFO)
mlogger = logging.getLogger('bnpp')

from qmmc.sampler import BNPPGibbsSampler
from qmmc.market import GaussianQuoteMarket, SEPQuoteMarket

def main():
  """ Main script.
  
  The bnpp-python.csv file is generated by the R/loadData.R script
  """
  
  # Create folder to save the results of the run.
  savedir = '.'
  if not os.path.exists(savedir):
      os.makedirs(savedir)

  # Load BNPP's data
  filepath = "../data/bnpp-python-onecust.csv"
  covar = {'NbDealers': {'type': "cat", 'ref': 2}}
  market = SEPQuoteMarket.load(filepath, covar=covar) 
  
  # Sample 100 x 100 times (save every 100 iterations)
  for _ in xrange(100):
    market.sample(100, sample_covar=True)
    print "Saving results."
    market.save(savedir)    

if __name__ == "__main__":
  main()
